### ISSUE TITLE
Use template instead of context data

### ISSUE THREAD

**Issue by agjohnson** [rtfd/sphinx-notfound-page#2]
Sphinx already has mechanisms for templating that I think would be more helpful than passing in the html content through a context variable. This should rely on a `4xx.html` or `404.html` (or both), so that the customer has complete control over how the page is rendered, not just the text that is used as part of the body.

**Comment by humitos** [comment]
@agjohnson it's not clear to me if you are thinking about using a file `404.rst` or just allowing the user to use a different template? If it's the later, you can customize this by defining `notfound_template` (I just added a test for this at https://github.com/rtfd/sphinx-notfound-page/commit/81ee85b)

Another possibility is to render a `404.rst` instead. Actually, if the user already has this file, it's being rendered and the links fixed by the extension. Although, after rendered this output is overriden by the extension because it does not check if the use already has a document for this page. I will fix this soon.

Using a `404.rst` file will produce a WARGNING, because this file will not be included in the toctree, though:

    checking consistency... docs/404.rst: WARNING: document isn't included in any toctree

**Comment by humitos** [comment]
> Another possibility is to render a `404.rst` instead. Actually, if the user already has this file, it's being rendered and the links fixed by the extension. Although, after rendered this output is overriden by the extension because it does not check if the use already has a document for this page. I will fix this soon.

This is done at https://github.com/rtfd/sphinx-notfound-page/commit/2a22e7f

I'm closing this issue. Feel free to reopen if you consider that the case that I'm covering here are not enough or are not what you meant in the original description.
